VideoGameList/VideoGameList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using VideoGameList.Models;
using System.Data;
using System.Text;
using System.Configuration;
using System.Data.SqlClient;


namespace VideoGameList.Controllers
{
    public class HomeController : Controller
    {
        private VideoGameContext context { get; set; }

        public HomeController(VideoGameContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var games = context.Games
                .Include(g => g.ESRB)
                .OrderBy(m => m.Title).ToList();
            return View(games);
        }
        public IActionResult AboutUs()
        {

            return View();
        }

        public IActionResult AboutHobby()
        {

            return View();
        }

        public IActionResult DBView()
        {
            var games = context.Games
                .Include(g => g.ESRB)
                .OrderBy(m => m.Title).ToList();
            return View(games);
        }


    }
}

VideoGameList/VideoGameList/Controllers/VideoGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VideoGameList.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace VideoGameList.Controllers
{
    public class VideoGameController : Controller
    {
        private VideoGameContext context { get; set; }

        public VideoGameController(VideoGameContext ctx)
        {
            context = ctx;
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.ESRB= context.ESRB.OrderBy(g => g.Name).ToList();
            return View("Edit", new VideoGame());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.ESRB = context.ESRB.OrderBy(g => g.Name).ToList();
            var game = context.Games.Find(id);
            return View(game);
        }
        [HttpPost]
        public IActionResult Edit(VideoGame game)
        {
            if (ModelState.IsValid)
            {
                if (game.VideoGameId == 0)
                    context.Games.Add(game);
                else
                    context.Games.Update(game);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (game.VideoGameId == 0) ? "Add" : "Edit";
                ViewBag.ESRB = context.ESRB.OrderBy(g => g.Name).ToList();
                return View(game);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var game = context.Games.Find(id);
            return View(game);
        }
        [HttpPost]
        public IActionResult Delete(VideoGame game)
        {
            context.Games.Remove(game);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

VideoGameList/VideoGameList/Views/Home/AboutHobby.cshtml
@{
    ViewData["Title"] = "About Video Games";
}

<h1>About Video Games</h1>

<body>
    <br />
<h3>Our Favorite Hobby</h3>
<p>For many people, video games are a fun way to spend free time.  Our team chose to create our final project based on our common favorite hobby of video games.
    We all enjoy playing different video games and trying out new games.  There are many different games and genres to try out. 
    We all enjoy video games because they transport us to a new reality and engage us to complete the game. 
    The pages we incorporated into our project include
    a video game list, add game, edit game, delete game, about us, about video games, and a HTML database view.  Our video game list page shows a table of video game
    ratings which include the game title, ESRB rating, genre, release date, and personal rating out of 5.  
</p>
<br />
<h3>History of Video Games</h3>
<p>
    Video games began in the 1950s and 1960s as computer scientists began designing simple games and simulations.  
    The first consumer video game hardware was released in the 1970s.  The first arcarde video games were Computer 
    Space and Pong.  There was then rapid growth with other arcade games such as Pac-Man.  Nintendo released its Nintendo 
    Entertainment System in 1985 which created a shift of improvement in the industry.  From then on Playstation was released, followed
    by the Xbox line and the Wii.  Gaming is constantly improving and now mobile gaming and casual gaming has become a larger market.  
    Hardware and software technology is continuing to improve in video games with support for HD video and for virtual and reality based games. 
</p>
<br />
<h3>Video Game Ratings</h3>
<p>
    Video game ratings are important because they inform players and parents who are purchasing video games for their children of the level of maturity.  
    ESRB ratings provide information about what is in a game or app so parents and consumers can make informed choices about which games are right for them.  
    The ESRB ratings are everyone, everyone 10+, teen, mature 17+, adults only 18+, and rating pending.  All console manufacturers as well as certain
    retailers and storefronts require ESRB ratings.  Ratings are also beneficial so that other players can see if they would enjoy the game. 
</p>
</body>

VideoGameList/VideoGameList/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}

<h1>About Us</h1>
<main>
    <style>
    img{
        max-width: 100%;
        max-height: 100%;
        display: block; /* remove extra space below image */
    }
    .box{
        width: 250px;        
        border: 5px solid black;
    }    
    .box.large{
        height: 300px;
    }
    .box.small{
        height: 100px;
    }
</style>
   <div class="box">
        <img src="/Images/GajicAlexImage.png" alt="Alex">
        <h3>Alexander Gajic</h3>
            <body>
                 About me: I am a third year Game Development Major.
            </body>
   </div>

   <div class="box">
        <img src="/Images/PetersIsabellaImage.png" alt="Isabella">
        <h3>Isabella Peters</h3>
            <body>
                 About me: I am a third year IT major on the software development track.
            </body>
   </div>

   <div class="box">
        <img src="/Images/ZhuKevinImage.png" alt="Kevin">
        <h3>Kevin Zhu</h3>
            <body>
                 About me: I'm in my third year studying software development track in Information Technology. <br />
            </body>
   </div>

   <div class="box">
        <img src="/Images/BurkeWilliamImage.png" alt="William">
        <h3>William Burke</h3>
            <body>
                 About Me: I am a part time student, 4th year on the Game Development track at CECH. <br />
            </body>

   </div>

   <div class="box">
        <img src="/Images/IkramHaseebImage.jpg" alt="Haseeb">
        <h3>Haseeb Ikram</h3>
            <body>
                 About Me: I am a fifth year in software development. <br />
            </body>
   </div>

</main>

VideoGameList/VideoGameList/Views/Home/DBView.cshtml
@model List<VideoGame>
@{
    ViewData["Title"] = "DBView";
}

<h1>DBView</h1>

<table class="table">
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.VideoGameId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ESRB.ESRBId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
        </tr>
}
    </tbody>
</table>

VideoGameList/VideoGameList/Views/Home/Index.cshtml
@model List<VideoGame>
@{
    ViewBag.Title = "Video Games";
}
<h1>Video Game List</h1>
<a asp-controller="VideoGame" asp-action="Add">Add Video Game</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>ESRB</th>
            <th>Genre</th>
            <th>Release Date</th>
            <th>Rating</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var game in Model)
        {
            <tr>
                <td>@game.Title</td>
                <td>@game.ESRB.Name</td>
                <td>@game.Genre</td>
                <td>@game.ReleaseDate</td>
                <td>@game.Rating</td>
                <td>
                    <a asp-controller="VideoGame" asp-action="Edit"
                       asp-route-id="@game.VideoGameId"
                       asp-route-slug="@game.Slug">Edit</a>
                    <a asp-controller="VideoGame" asp-action="Delete"
                       asp-route-id="@game.VideoGameId"
                       asp-route-slug="@game.Slug">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>